npm install gulp-cli
npm install gulp
npm install gulp-autoprefixer
npm install gulp-compile-handlebars
npm install gulp-concat
npm install gulp-connect
npm install jshint
npm install gulp-jshint
npm install gulp-jsonlint
npm install gulp-live-server
npm install gulp-merge-json
npm install gulp-rename
npm install gulp-sass
npm install gulp-uglify
npm install nodemailer
npm install ansi-colors
npm install fancy-log
npm install http-proxy-middleware
npm install body-parser
npm install express
